// Weapon data. The numbers sit inside the ranges the genre has settled on
// (assault rifle about 700-850 RPM, SMG about 780-1050 RPM, ADS times in the
// 175-300 ms band) so the guns feel familiar instead of arbitrary. They are
// design targets for this project, not measurements taken from another game.
// What CI proves is the relationships: rate of fire independent of frame rate,
// monotonic damage falloff, and time to kill inside a stated window.

export const WEAPONS = {
  ar: {
    id: 'ar',
    name: 'KR-7 CARBINE',
    kind: 'Assault Rifle',
    rpm: 780,
    auto: true,
    magSize: 30,
    reserve: 210,
    reloadMs: 2150,
    reloadEmptyMs: 2750,
    adsMs: 250,
    unAdsMs: 200,
    hipFovH: 103,
    adsFovH: 74,
    viewFov: 62,
    damageNear: 33,
    damageFar: 22,
    falloffStart: 26,
    falloffEnd: 70,
    headMult: 1.55,
    hipSpread: 2.1,
    adsSpread: 0.16,
    spreadPerShot: 0.13,
    recoil: { pitchBase: 0.31, yawDrift: 0.11, randomShare: 0.18, driftSign: 1 },
    kickBack: 0.016,
    camRecoilShare: 0.34,
    muzzleFlashMs: 42,
    tracerEvery: 3,
    sound: { bodyHz: 168, bodyDecay: 0.10, crackHp: 2400, mech: 1.0, tailWet: 0.16 },
  },
  smg: {
    id: 'smg',
    name: 'VX-9 SMG',
    kind: 'Submachine Gun',
    rpm: 920,
    auto: true,
    magSize: 36,
    reserve: 252,
    reloadMs: 1850,
    reloadEmptyMs: 2350,
    adsMs: 195,
    unAdsMs: 155,
    hipFovH: 106,
    adsFovH: 80,
    viewFov: 64,
    damageNear: 28,
    damageFar: 16,
    falloffStart: 14,
    falloffEnd: 42,
    headMult: 1.4,
    hipSpread: 1.7,
    adsSpread: 0.24,
    spreadPerShot: 0.15,
    recoil: { pitchBase: 0.24, yawDrift: 0.15, randomShare: 0.26, driftSign: -1 },
    kickBack: 0.012,
    camRecoilShare: 0.30,
    muzzleFlashMs: 36,
    tracerEvery: 4,
    sound: { bodyHz: 205, bodyDecay: 0.075, crackHp: 2800, mech: 0.85, tailWet: 0.13 },
  },
  dmr: {
    id: 'dmr',
    name: 'M-14 MARKSMAN',
    kind: 'Marksman Rifle',
    rpm: 360,
    auto: false,
    magSize: 20,
    reserve: 120,
    reloadMs: 2350,
    reloadEmptyMs: 2950,
    adsMs: 320,
    unAdsMs: 250,
    hipFovH: 100,
    adsFovH: 46,
    viewFov: 58,
    damageNear: 62,
    damageFar: 48,
    falloffStart: 40,
    falloffEnd: 110,
    headMult: 1.7,
    hipSpread: 3.0,
    adsSpread: 0.05,
    spreadPerShot: 0.22,
    recoil: { pitchBase: 0.62, yawDrift: 0.12, randomShare: 0.15, driftSign: 1 },
    kickBack: 0.028,
    camRecoilShare: 0.42,
    muzzleFlashMs: 55,
    tracerEvery: 1,
    sound: { bodyHz: 128, bodyDecay: 0.15, crackHp: 2000, mech: 1.25, tailWet: 0.22 },
  },
};

export const WEAPON_ORDER = ['ar', 'smg', 'dmr'];

/** CoD-style horizontal FOV -> three.js vertical FOV. */
export function hFovToV(hDeg, aspect) {
  const h = (hDeg * Math.PI) / 180;
  return (2 * Math.atan(Math.tan(h / 2) / aspect) * 180) / Math.PI;
}
